### PR TITLE
Put Bittrex specifics in a separate project.

### PR DESCRIPTION
**Pull request by jgsnijders**
I have put the Bittrex specific code in a newly created project to keep this from getting tightly coupled to the more generic part.

### CODE REVIEW

**Comment by sthewissen** [comment]
I hope to be able to look into this today to see if we can merge it back into master. Should have a rather clear schedule from today onwards :)

**Comment by jgsnijders** [comment]
@sthewissen, what would be the best way forward? Pushing our work into the dev branch and continue to work on that branch? If you can arrange things so that it's okay with you, we'll switch to one of your branches.

**Comment by sthewissen** [comment]
That was the idea yeah. I'm trying to find Gabriels account but can't seem to find it on Github...

**Comment by jgsnijders** [comment]
His account is gabrielvdk

**Comment by sthewissen** [comment]
@jgsnijders @gabrielvdk Would it be an idea to create a Telegram chat to talk about this thing and have a chat on where we think we should take it etc?

**Comment by jgsnijders** [comment]
Good idea. Maybe you and Gabriël can initiate that via Twitter?

**Pull request merged**
